In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [11]:
df = pd.read_csv("raw_skills.csv")
df

,role,skills
0,Data Scientist,Python SQL Machine Learning Statistics Data An...
1,DevOps Engineer,AWS Docker Kubernetes CI CD Automation Linux C...
2,Backend Developer,Java Python SQL APIs Spring Boot REST Databases
3,Frontend Developer,JavaScript React CSS HTML Web Design UI UX
4,Cloud Architect,Cloud Computing AWS Azure Automation Networkin...
5,Data Engineer,Python SQL ETL Spark Hadoop Data Pipelines Clo...
6,Machine Learning Engineer,Python Machine Learning TensorFlow Keras Deep ...
7,Mobile App Developer,Java Kotlin Swift Mobile Development Android iOS
8,Cybersecurity Analyst,Network Security Penetration Testing Linux Pyt...
9,Database Administrator,SQL Databases Backup Recovery Performance Tuni...
10,Full Stack Developer,JavaScript Python SQL React Node APIs Web Design
11,QA Automation Engineer,Automation Testing Selenium Python CI CD Quali...
12,System Administrator,Linux Networking Automation Bash Scripting Ser...
13,Business Analyst,SQL Data Analysis Excel Reporting Statistics C...
14,AI Research Engineer,Python Machine Learning Deep Learning Research...

In [21]:
vectorizer = TfidfVectorizer(lowercase=True)
role_vectors = vectorizer.fit_transform(df["skills"])

print("Vocabulary size:", len(vectorizer.vocabulary_))
print(vectorizer.get_feature_names_out())

Vocabulary size: 74
['analysis' 'android' 'apis' 'assessment' 'assurance' 'automation' 'aws'
 'azure' 'backup' 'bash' 'boot' 'cd' 'ci' 'cloud' 'communication'
 'computing' 'css' 'data' 'databases' 'deep' 'deployment' 'design'
 'development' 'docker' 'etl' 'excel' 'hadoop' 'html' 'ios' 'java'
 'javascript' 'keras' 'kotlin' 'kubernetes' 'learning' 'linux' 'machine'
 'management' 'mathematics' 'mobile' 'model' 'mysql' 'network'
 'networking' 'node' 'numpy' 'oracle' 'pandas' 'penetration' 'performance'
 'pipelines' 'python' 'quality' 'react' 'recovery' 'reporting' 'research'
 'rest' 'risk' 'scripting' 'security' 'selenium' 'server' 'spark' 'spring'
 'sql' 'statistics' 'swift' 'tensorflow' 'testing' 'tuning' 'ui' 'ux'
 'web']

In [24]:
num_skills = 3

user_skills = []
print(f"Enter at least {num_skills} skills, one at a time.")
for i in range(num_skills):
    skill = input(f"Skill {i+1}: ")
    user_skills.append(skill)

print("\nYour entered skills:", user_skills)

user_text = " ".join(user_skills)
user_vector = vectorizer.transform([user_text])

Enter at least 3 skills, one at a time.

Your entered skills: ['python', 'deep learning', 'machine learning']

In [25]:
scores = cosine_similarity(user_vector, role_vectors).flatten()
df["match_score"] = scores
df[["role", "match_score"]]

                         role  match_score
0              Data Scientist     0.428501
1             DevOps Engineer     0.000000
2           Backend Developer     0.053862
3          Frontend Developer     0.000000
4             Cloud Architect     0.000000
5               Data Engineer     0.051547
6   Machine Learning Engineer     0.707906
7        Mobile App Developer     0.000000
8       Cybersecurity Analyst     0.051728
9      Database Administrator     0.000000
10       Full Stack Developer     0.056269
11     QA Automation Engineer     0.053224
12       System Administrator     0.000000
13           Business Analyst     0.000000
14       AI Research Engineer     0.779164

In [26]:
top_matches = df.sort_values("match_score", ascending=False).head(3)
top_matches[["role", "match_score"]]

                         role  match_score
14       AI Research Engineer     0.779164
6   Machine Learning Engineer     0.707906
0              Data Scientist     0.428501

In [27]:
print("Your skills:", user_skills)
print("\nTop", 3, "recommended career paths:\n")
for i, row in enumerate(top_matches.itertuples(), start=1):
    print(f"{i}. {row.role}  (match score: {row.match_score:.2f})")

Your skills: ['python', 'deep learning', 'machine learning']

Top 3 recommended career paths:

1. AI Research Engineer  (match score: 0.78)
2. Machine Learning Engineer  (match score: 0.71)
3. Data Scientist  (match score: 0.43)